#!/bin/sh

zero="$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')"

while read -r local_ref local_oid remote_ref remote_oid; do
	if [ "$remote_ref" = "refs/heads/main" ]; then
		if [ "$local_oid" = "$zero" ]; then
			# maybe don't allow deleting the main branch
			echo >&2 "Attempted to delete remote main branch, aborting"
			exit 1
		fi

		if [ "$remote_oid" = "$zero" ]; then
			range="$local_oid"
		else
			range="$remote_oid..$local_oid"
		fi

		bad_commit="$(git rev-list -n 1 --invert-grep --grep '^Reviewed-by:' "$range")"
		if [ -n "$bad_commit" ]; then
			echo >&2 "Found unreviewed commit $(git rev-parse --short "$bad_commit") in push to main, aborting"
			exit 1
		fi
	fi
done

exit 0
