.Dd $Mdocdate: May 14 2021 $
.Dt TRUE 1
.Os uspace

.Sh NAME
.Nm true ,
.Nm false
.Nd return with success or failure exit codes

.Sh SYNOPSIS
.Nm true
.Nm false

.Sh DESCRIPTION
The
.Nm true
and
.Nm false
utilities will return with exit codes 0 and 1 respectively.

.Sh STANDARDS
The
.Nm true
and
.Nm false
utilities are compliant with the
.St -p1003.1-2008
specification.

.Sh AUTHORS
The uspace implementations of
.Nm true
and
.Nm false
were written by
.An Samadi van Koten Aq Mt samadi@vktec.org.uk
