.Dd $Mdocdate: May 13 2021 $
.Dt YES 1
.Os uspace

.Sh NAME
.Nm yes
.Nd output string repeatedly

.Sh SYNOPSIS
.Nm
.Op Ar string...

.Sh DESCRIPTION
The
.Nm
utility outputs arguments to standard output - 'y' if no string given - followed by a new line until killed.

.Sh AUTHORS
The uspace implementation of
.Nm
was written by
.An Ellis Trisk-Grove Aq Mt ellis@trisk-grove.com
